### ISSUE TITLE
Improve modification of in-progress tasks

### ISSUE THREAD

**Issue by luxaritas** [unobserved-io/Furtherance#115]
There's a small workflow thing I'm missing coming from Hamster. I tend to be a forgetful person and not swap tasks when I should. It would be great to be able to:
* Modify the start time of a timer while it is running for it (eg, if I really wanted to start the timer 20 minutes ago, I don't need to create a separate entry and then start a new timer)
* Edit an existing timer to remove the end time, allowing me to "continue" it without a gap between when it originally ended and when I'm restarting it

**Comment by lakoliu** [comment]
Hi, @luxaritas. You and me both! I always forget to start a task, or change my task. I think the ability to modify the start time would be great, so I'll definitely add that to the list. As for allowing the user to continue an existing timer, that sounds really cool, but I'm having trouble thinking of exactly how it would work in practice. I'll definitely keep it on my mind though and try to work it in. Thanks for the suggestions!

Also, I've never heard of Hamster, so I'm definitely going to look into that for inspiration. Thanks!

**Comment by luxaritas** [comment]
Related: Would be great to be able to modify the task description while it is currently tracking

**Comment by Eloitor** [comment]
It would be nice to to be able to discount time if I forgot to stop the timer.

**Comment by rickykresslein** [comment]
This feature has been added to the Iced re-write. You can now change the task name/tags/project/rate while the timer is running, as well as the start time.
