### ISSUE TITLE
In report page, show not only time, but also date!

### ISSUE THREAD

**Issue by sverro2** [unobserved-io/Furtherance#117]
When the report dialog is opened, it would be beneficial to see the date a task had been worked on (especially when your report is created for the last 180 days or even for a year).

**Comment by lakoliu** [comment]
That's a good idea. I will look into what this would look like. I just don't want the reports to look too cluttered.

**Comment by Scridgeon** [comment]
I would also love this feature!

**Comment by rickykresslein** [comment]
Reports have changed in the new Iced re-write to include charts with dates.
