### ISSUE TITLE
Migrate to Adaptive Dialogs (Libadwaita 1.5)

### ISSUE THREAD

**Issue by gabrbrand** [unobserved-io/Furtherance#130]
See https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/migrating-to-adaptive-dialogs.html

- [ ] Port AdwAboutWindow to AdwAboutDialog
- [ ] Port AdwPreferencesWindow to AdwPreferencesDialog
- [ ] Port to AdwAlertDialog
- [ ] Port (AdwWindow) to AdwDialog

**Comment by rickykresslein** [comment]
Since the app is being ported to Iced, this is no longer planned. However, the GTK branch will stick around and PR's are welcome.
