### ISSUE TITLE
Notify when the timer is not running 

### ISSUE THREAD

**Issue by amal-chandran** [unobserved-io/Furtherance#133]
- when you detect the idle for some time & when timer is not in running state 
- can we show a notification like lets do some work
- there are times i forget to start timer 
- it would be great if you can add a indicator icon also

**Comment by lakoliu** [comment]
Yes, this is something I want to implement. Thank you for the suggestion. My plan is to create a setting that allows the user to have a notification remind them to set a timer when they open a certain app(s). Not sure when I will be able to get to this, but it is at the top of the list!

**Comment by rickykresslein** [comment]
I just implemented reminder notifications. In the future I plan on making them application aware, so you could get notifications to start a timer only when you open [Kdenlive](https://invent.kde.org/multimedia/kdenlive), for example. For now, a user-set interval will do. Thanks for your patience!
