### ISSUE TITLE
`Auto` theme option doesn't work properly on GNOME

### ISSUE THREAD

**Issue by salim-b** [unobserved-io/Furtherance#150]
I just updated to the new Furtherance (24.10.2) that's based on Iced instead of GTK4 / libadwaita and noticed that the *Theme* option `Auto` is not respected on my system ([Bluefin](https://docs.projectbluefin.io/) which is based on Fedora Silverblue; [`bluefin-dx:gts`](https://github.com/ublue-os/bluefin/pkgs/container/bluefin-dx/285415329?tag=gts) which is currently on GNOME 45.6).

Selecting `Dark` manually works fine.

Thank you very much for the great app and continued development! ❤️

**Comment by rickykresslein** [comment]
If you start Furtherance with the theme selector on Auto and the system theme is Dark, does Furtherance open in Light theme? Or does it only not respect it when you switch the system theme while the app is open?

**Comment by salim-b** [comment]
> If you start Furtherance with the theme selector on Auto and the system theme is Dark, does Furtherance open in Light theme?

Yes, it opens in Light theme when the GNOME system theme is Dark.

> Or does it only not respect it when you switch the system theme while the app is open?

Switching the GNOME system theme has no effect while Furtherance is open and the `Auto` theme option is selected. And selecting `Auto` always results in the Light theme regardless of the system theme.

**Comment by rickykresslein** [comment]
Interesting, when I test it on stock Fedora 40 it works. I'll look into Bluefin/Silverblue and get back to you. The theme switching uses [dark-light](https://github.com/frewsxcv/rust-dark-light), so it could be an upstream issue there. Thanks for bringing up this issue!

**Comment by salim-b** [comment]
I forgot to mention that I'm using the [Flatpak](https://flathub.org/apps/io.unobserved.furtherance).

**Comment by salim-b** [comment]
The same problem also occurs under Ubuntu 22.04 (Gnome 42.9) using the Flatpak.
