### ISSUE TITLE
Touchpad scroll direction is inverted under GNOME

### ISSUE THREAD

**Issue by salim-b** [unobserved-io/Furtherance#151]
In Furtherance 24.10.2, **touchpad scroll direction** is inverted on my system ([Bluefin](https://docs.projectbluefin.io/) which is based on Fedora Silverblue; [`bluefin-dx:gts`](https://github.com/ublue-os/bluefin/pkgs/container/bluefin-dx/285415329?tag=gts) which is currently on GNOME 45.6).

When I set touchpad scroll direction to "Traditional" (Scrolling moves the view) in Gnome settings, the direction is actually "Natural" (Scrolling moves the content) in Furtherance – and vice versa. So far, Furtherance is the only app I observed the scrolling direction to be inverted.

I'm using the [Flatpak](https://flathub.org/apps/io.unobserved.furtherance).

**Comment by rickykresslein** [comment]
Thanks, I will look into this. I assume it is an upstream issue with Iced, but I'll check.

**Comment by rickykresslein** [comment]
This was an upstream issue that had already been fixed  (https://github.com/iced-rs/iced/pull/2583) and for some reason cargo had not updated iced to 0.13.1. `Cargo.lock` has been updated and this fixed will be included in the next release.
