### ISSUE TITLE
`days_to_show` is forced to a maximum of `364` in the UI

### ISSUE THREAD

**Issue by salim-b** [unobserved-io/Furtherance#153]
By default, the `days_to_show` setting is set to `365`. When trying to change the setting via the UI, it is forced to a maximum of `364` and can't be reset to the initial value of `365` again without manually changing the `settings.toml` file.

This is on Furtherance v24.10.2.

**Comment by rickykresslein** [comment]
Thanks, I will fix this asap.

**Comment by rickykresslein** [comment]
Fixed. Will be in the next release.
