### ISSUE TITLE
TAB key to switch between input fields while adding New shortcut

### ISSUE THREAD

**Issue by vinyatu** [unobserved-io/Furtherance#157]
Please allow TAB key to switch between input fields while adding New shortcut.
It's amazing that this simple keyboard workflow doesn't work here, as it's pretty useful.
Is it possible to add it quickly?

**Comment by rickykresslein** [comment]
Hey, thanks for posting this. I thought Iced didn't support this upstream yet, but it looks like there is a way to do it now since last time I checked. I will implement this as soon as I get the chance.
