### ISSUE TITLE
Pomodoro countdown, logs break length not timer length

### ISSUE THREAD

**Issue by RezaSR** [unobserved-io/Furtherance#159]
In a Pomodoro countdown timer, after the timer ends, clicking "Break" records the break duration in the history (actual start time + break duration).
By clicking "Stop", it records the correct duration though.

**Comment by rickykresslein** [comment]
Thank you for reporting this. I will look into it and get back to your or get to work fixing it.

**Comment by rickykresslein** [comment]
I found the bug and fixed it. It will be in the next release. Thanks!

**Comment by RezaSR** [comment]
Great! Thank you so much for quick fix!

**Comment by rickykresslein** [comment]
Will do!
