### ISSUE TITLE
Error when attempting to log in to sync server

### ISSUE THREAD

**Issue by jibsaramnim** [unobserved-io/Furtherance#160]
Hi there! I wanted to give the new sync functionality a try to see how it might fit into my work setup, so spun up a local instance but I ran into an issue. I was able to verify that the same issue occurs when attempting to log in to the official server.

The application just shows a "Login failed" message when I try to log in, but the logs show a bit more:

```log
Error logging in: Network(reqwest::Error { kind: Request, url: "https://sync.furtherance.app/api/login", source: hyper_util::client::legacy::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })) })
```

The error was exactly the same when attempting to log in to my self-hosted server.

Attempting to connect with the sync server works fine via the browser (from the same machine I'm running Furtherance on). I also took a peek at your code and was able to make a curl request work just fine. I used this, if this helps (again, from the same machine):

```bash
❯ curl -H "Content-Type: application/json" -d '{"email": "******", "encryption_key": "******", "device_id": "foo"}' https://furtherance.******/api/login
{"access_token":"******","refresh_token":"******"}
```

Note: details obfuscated by me, real looking access and refresh tokens were returned from my self-hosted instance. I did not try this with the official server as I don't have an account there (yet).

Do you happen to know what might be causing this?

Some more information:
- Running Furtherance v24.12.0  (Flatpak release) on Fedora Linux 41 Silverblue
- Running Furtherance Sync on a server running Debian 12 (using your docker compose file, somewhat customized to fit my setup), up-to-date

Thank you kindly!

**Comment by rickykresslein** [comment]
Hi! Thank you for reporting this. I'm pretty sure this is due to a big oversight on my part with the Flatpak manifest. I didn't add network sharing, which is why Furtherance can't reach the URL. I will update it asap. Again, thank you so much for bringing this to my attention. I'm not using the Flatpak myself and a lot of the issues with the app seem to stem from the containerization. I need to do a better job at testing for that 😬

**Comment by rickykresslein** [comment]
I updated the Flatpak manifest and submitted it to Flathub. I tested it and it seems to work as it should. Once it is up on Flathub (usually takes a couple of hours), please test it and let me know if there is still an issue. Thanks for always helping to make Furtherance better! I greatly appreciate it.

**Comment by jibsaramnim** [comment]
Thanks so much for the quick turn-around! Manually enabling this permission seems to fix it for me too, very nice!

In case anyone else wants to follow along, relevant PR is here: flathub/io.unobserved.furtherance#13
