### ISSUE TITLE
Add hourly rate

### ISSUE THREAD

**Issue by Gotterbild** [unobserved-io/Furtherance#43]
It would be awesome to have ability to enter a hourly rate and a currency.

In order not to think about what currencies to add, you can just add a separate input for currency symbol and a checkbox to display it before or after the number.

I mean different currencies (and different countries) have different rules for currency sign placement: `$100`, `100 €`.

With adding the hourly rate it will be also great to add ability to export certain interval into PDF or even a complete invoice (I can provide invoice example). However, that is definitely a separate issue.

**Comment by lakoliu** [comment]
Thanks for your suggestion. I think this is a good idea that will be useful for a lot of people. I will plan on working on this once I've implemented reports (Issue #32). I will probably ask some questions then because this is not a feature that I would use so I'll need some input on how to best implement it.

**Comment by Gotterbild** [comment]
@lakoliu 
Yeah, sure. Go ahead. I'm answer your questions with pleasure.

**Comment by Gotterbild** [comment]
@lakoliu 
After thinking a bit and looking at other apps I think Project entity will be required.

Situation: I have several clients. I want tracked time for these clients to be completely separate. Also, I have a different rate for each client in different currencies (USD, EUR).

However, I do understand no everyone will use app for working with clients. Someone would just want to track time for their different personal projects separately.

That's why I think Projects is a good name.

A hourly rate and a currency would be then set up for each project individually.

**Comment by rickykresslein** [comment]
This feature has now been added to the Iced re-write, so I will close this issue. You can build it yourself now and the release is coming very soon. It does not currently support different currencies (only USD), but the ability is already built into the database and it will be coming soon.
