### ISSUE TITLE
Unable to move window while I have an "edit task" window open

### ISSUE THREAD

**Issue by bordam** [unobserved-io/Furtherance#69]
So basically unlike the task view, which has a hidden, draggable titlebar, and the preferences, you can't move the window while you are editing a task. This could theoretically speaking be annoying, e.g. if you want to check a calendar app to see what time to insert task and furtherance is on the data you want to see. You should, in such case, cancel the edit, move the window and reopen the edit, or move the calendar app. Honestly it's definitely not a big deal but being able to drag the Edit task window would be nice.

**Comment by lakoliu** [comment]
Thanks, I definitely see the benefit of that. I will look into if this can be changed.

**Comment by flxzt** [comment]
FYI you can move the window without title bars by holding the meta key + dragging with the mouse from anywhere on the active window. @lakoliu there is the possibility of adding a headerbar to the message dialog with the [builder](https://gtk-rs.org/gtk4-rs/stable/0.4/docs/gtk4/builders/struct.MessageDialogBuilder.html) (look for the use_header_bar method)

**Comment by rickykresslein** [comment]
With the Iced re-write, this bug no longer exists. The `edit task` window has been moved to the right sidebar.
